namespace gapt

open tactic expr

namespace lk

lemma LogicalAxiom {a} (main1 : a) (main2 : ¬a) : false := main2 main1
lemma BottomAxiom (main : false) : false := main
lemma TopAxiom (main : ¬true) : false := main ⟨⟩
lemma ReflexivityAxiom {α : Type} {a : α} (main : a ≠ a) : false := main (eq.refl a)
lemma NegLeftRule {a} (main : ¬a) (aux : ¬¬a) : false := aux main
lemma NegRightRule {a} (main : ¬¬a) (aux : ¬a) : false := main aux
lemma AndLeftRule {a b} (main : a ∧ b) (aux : a → b → false) : false :=
aux main.left main.right
lemma AndRightRule {a b} (main : ¬(a ∧ b)) (aux1 : ¬¬a) (aux2 : ¬¬b) : false :=
aux1 $ λa, aux2 $ λb, main ⟨a,b⟩
lemma OrLeftRule {a b} (main : a ∨ b) (aux1 : ¬a) (aux2 : ¬b) : false :=
begin cases main, contradiction, contradiction end
lemma OrRightRule {a b} (main : ¬(a ∨ b)) (aux : ¬a → ¬b → false) : false :=
aux (main ∘ or.inl) (main ∘ or.inr)
lemma ImpLeftRule {a b} (main : a → b) (aux1 : ¬¬a) (aux2 : ¬b) : false := aux1 (aux2 ∘ main)
lemma ImpRightRule {a b : Prop} (main : ¬(a → b)) (aux : a → ¬b → false) : false :=
main (classical.by_contradiction ∘ aux)
lemma ForallLeftRule {α} {P : α → Prop} (t) (main : ∀x, P x) (aux : ¬P t) : false := aux (main t)
lemma ForallRightRule {α} {P : α → Prop} (main : ¬∀x, P x) (aux : Πx, ¬P x → false) : false :=
begin apply main, intro x, apply classical.by_contradiction, intro, apply aux, assumption end
lemma ExistsLeftRule {α} {P : α → Prop} (main : ∃x, P x) (aux : Πx, P x → false) : false :=
begin cases main, apply aux, assumption end
lemma ExistsRightRule {α} {P : α → Prop} (t) (main : ¬∃x, P x) (aux : ¬¬P t) : false :=
begin apply aux, intro hp, apply main, existsi t, assumption end
lemma EqualityLeftRule1 {α} (c : α → Prop) (t s) (main1 : t=s) (main2 : c s) (aux : ¬c t) : false :=
begin apply aux, rw main1, assumption end
lemma EqualityRightRule1 {α} (c : α → Prop) (t s) (main1 : t=s) (main2 : ¬c s) (aux : ¬¬c t) : false :=
begin apply aux, rw main1, assumption end
lemma EqualityLeftRule2 {α} (c : α → Prop) (t s) (main1 : s=t) (main2 : c s) (aux : ¬c t) : false :=
EqualityLeftRule1 c t s main1.symm main2 aux
lemma EqualityRightRule2 {α} (c : α → Prop) (t s) (main1 : s=t) (main2 : ¬c s) (aux : ¬¬c t) : false :=
EqualityRightRule1 c t s main1.symm main2 aux
lemma CutRule (a : Prop) (aux1 : ¬¬a) (aux2 : ¬a) : false := aux1 aux2

lemma unpack_target_disj.cons {a b} (next : ¬a → b) : a ∨ b :=
classical.by_cases or.inl (or.inr ∘ next)
lemma unpack_target_disj.singleton {a} : ¬¬a → a := classical.by_contradiction
private meta def unpack_target_disj : list name → command
| [] := skip
| [h] := do tgt ← target,
            apply $ app (const ``gapt.lk.unpack_target_disj.singleton []) tgt,
            intro h, skip
| (h::hs) := do tgt ← target,
                a ← return $ tgt.app_fn.app_arg,
                b ← return $ tgt.app_arg,
                apply $ app_of_list (const ``gapt.lk.unpack_target_disj.cons []) [a, b],
                intro h,
                unpack_target_disj hs

meta def sequent_formula_to_hyps (ant suc : list name) : command := do
intro_lst ant, unpack_target_disj suc

end lk

end gapt

noncomputable theory

namespace gapt_export

def all {a : Type} (P : a -> Prop) := ∀x, P x

constant i : Type

constant difference : (i -> (i -> i))

constant b : i

constant a1 : i

constant product : (i -> (i -> i))

constant quotient : (i -> (i -> i))

constant d : (i -> (i -> (i -> Prop)))

constant b1 : i

constant c2 : i

constant c1 : i

constant c : i

constant a : i

constant m : (i -> (i -> (i -> Prop)))

constant b2 : i

lemma lk_proof : ((∀ B : i, (∀ A : i, ((quotient (product A B) B) = A))) -> ((∀ X3 : i, (∀ X4 : i, (∀ X5 : i, (and ((m X3 X4 X5) -> ((product (product X3 X4) (product X4 X5)) = (product X3 X5))) (((product (product X3 X4) (product X4 X5)) = (product X3 X5)) -> (m X3 X4 X5)))))) -> ((∀ B : i, (∀ A : i, ((product (quotient A B) B) = A))) -> ((∀ B : i, (∀ A : i, ((product (product (product A B) B) (product B (product B A))) = B))) -> ((∀ X0 : i, (∀ X1 : i, (∀ X2 : i, (and ((d X0 X1 X2) -> ((product X0 X1) = (product X1 X2))) (((product X0 X1) = (product X1 X2)) -> (d X0 X1 X2)))))) -> ((∀ A : i, ((product A A) = A)) -> ((∀ D : i, (∀ C : i, (∀ B : i, (∀ A : i, ((product (product A B) (product C D)) = (product (product A C) (product B D))))))) -> ((∀ B : i, (∀ A : i, ((product A (difference A B)) = B))) -> ((∀ B : i, (∀ A : i, ((difference A (product A B)) = B))) -> ((d a b c1) -> ((d a b1 c) -> ((d a1 b2 c1) -> ((d a1 b c) -> ((d a1 b1 c2) -> (m b1 b b2))))))))))))))) :=
begin
gapt.lk.sequent_formula_to_hyps [`hyp.h_0, `hyp.h_1, `hyp.h_2, `hyp.h_3, `hyp.h_4, `hyp.h_5, `hyp.h_6, `hyp.h_7, `hyp.h_8, `hyp.h_9, `hyp.h_10, `hyp.h_11, `hyp.h_12, `hyp.h_13] [`hyp.h_14],
apply (gapt.lk.ForallLeftRule b2 hyp.h_0), intros hyp.h_15,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_0), intros hyp.h_16,
apply (gapt.lk.ForallLeftRule c hyp.h_0), intros hyp.h_17,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_0), intros hyp.h_18,
apply (gapt.lk.ForallLeftRule b1 hyp.h_0), intros hyp.h_19,
apply (gapt.lk.ForallLeftRule b hyp.h_0), intros hyp.h_20,
apply (gapt.lk.ForallLeftRule (product b (quotient c b)) hyp.h_20), intros hyp.h_21,
apply (gapt.lk.ForallLeftRule (product b (quotient (product b (quotient b1 b)) b)) hyp.h_20), intros hyp.h_22,
apply (gapt.lk.ForallLeftRule a hyp.h_20), intros hyp.h_23,
apply (gapt.lk.ForallLeftRule (product b (quotient (quotient b1 b) b)) hyp.h_20), intros hyp.h_24,
apply (gapt.lk.ForallLeftRule (product b (quotient c1 b)) hyp.h_20), intros hyp.h_25,
apply (gapt.lk.ForallLeftRule (product b (quotient (product b b1) b)) hyp.h_20), intros hyp.h_26,
apply (gapt.lk.ForallLeftRule (product b (quotient b1 b)) hyp.h_20), intros hyp.h_27,
apply (gapt.lk.ForallLeftRule a1 hyp.h_20), intros hyp.h_28,
apply (gapt.lk.ForallLeftRule (product b1 (quotient c2 b1)) hyp.h_19), intros hyp.h_29,
apply (gapt.lk.ForallLeftRule a hyp.h_19), intros hyp.h_30,
apply (gapt.lk.ForallLeftRule (product b1 (quotient c b1)) hyp.h_19), intros hyp.h_31,
apply (gapt.lk.ForallLeftRule a1 hyp.h_19), intros hyp.h_32,
apply (gapt.lk.ForallLeftRule (difference (difference b1 b) b) hyp.h_19), intros hyp.h_33,
apply (gapt.lk.ForallLeftRule (difference (difference (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_18), intros hyp.h_34,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) (quotient b2 (difference b1 b))) hyp.h_18), intros hyp.h_35,
apply (gapt.lk.ForallLeftRule (product b (quotient (product (difference b1 b) b1) b)) hyp.h_17), intros hyp.h_36,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_17), intros hyp.h_37,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (quotient (quotient (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2))) hyp.h_16), intros hyp.h_38,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (quotient (product (product (difference b1 b) b2) (quotient (difference b1 b) (product (difference b1 b) b2))) (product (difference b1 b) b2))) hyp.h_16), intros hyp.h_39,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (quotient (product (product (difference b1 b) b2) (difference b1 b)) (product (difference b1 b) b2))) hyp.h_16), intros hyp.h_40,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (quotient (difference b1 b) (product (difference b1 b) b2))) hyp.h_16), intros hyp.h_41,
apply (gapt.lk.ForallLeftRule (product b2 (quotient (difference b2 (product (difference b1 b) b2)) b2)) hyp.h_15), intros hyp.h_42,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_15), intros hyp.h_43,
apply (gapt.lk.ForallLeftRule (product b2 (quotient c1 b2)) hyp.h_15), intros hyp.h_44,
apply (gapt.lk.ForallLeftRule a1 hyp.h_15), intros hyp.h_45,
apply (gapt.lk.ForallLeftRule b1 hyp.h_1), intros hyp.h_46,
apply (gapt.lk.ForallLeftRule b hyp.h_46), intros hyp.h_47,
apply (gapt.lk.ForallLeftRule b2 hyp.h_47), intros hyp.h_48,
apply (gapt.lk.ForallLeftRule b2 hyp.h_2), intros hyp.h_49,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_2), intros hyp.h_50,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_2), intros hyp.h_51,
apply (gapt.lk.ForallLeftRule b1 hyp.h_2), intros hyp.h_52,
apply (gapt.lk.ForallLeftRule b hyp.h_2), intros hyp.h_53,
apply (gapt.lk.ForallLeftRule (product b (product b b1)) hyp.h_53), intros hyp.h_54,
apply (gapt.lk.ForallLeftRule c hyp.h_53), intros hyp.h_55,
apply (gapt.lk.ForallLeftRule c1 hyp.h_53), intros hyp.h_56,
apply (gapt.lk.ForallLeftRule b1 hyp.h_53), intros hyp.h_57,
apply (gapt.lk.ForallLeftRule (quotient b1 b) hyp.h_53), intros hyp.h_58,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b1) hyp.h_53), intros hyp.h_59,
apply (gapt.lk.ForallLeftRule (difference (product b1 b) b) hyp.h_53), intros hyp.h_60,
apply (gapt.lk.ForallLeftRule c hyp.h_52), intros hyp.h_61,
apply (gapt.lk.ForallLeftRule c2 hyp.h_52), intros hyp.h_62,
apply (gapt.lk.ForallLeftRule b hyp.h_52), intros hyp.h_63,
apply (gapt.lk.ForallLeftRule b2 hyp.h_51), intros hyp.h_64,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_50), intros hyp.h_65,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (difference b1 b)) hyp.h_50), intros hyp.h_66,
apply (gapt.lk.ForallLeftRule (difference (product (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_50), intros hyp.h_67,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (quotient (difference b1 b) (product (difference b1 b) b2))) hyp.h_50), intros hyp.h_68,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (product (product (difference b1 b) b2) (difference b1 b))) hyp.h_50), intros hyp.h_69,
apply (gapt.lk.ForallLeftRule (quotient (difference b1 b) (product (difference b1 b) b2)) hyp.h_50), intros hyp.h_70,
apply (gapt.lk.ForallLeftRule (difference b2 (product (difference b1 b) b2)) hyp.h_49), intros hyp.h_71,
apply (gapt.lk.ForallLeftRule c1 hyp.h_49), intros hyp.h_72,
apply (gapt.lk.ForallLeftRule c hyp.h_3), intros hyp.h_73,
apply (gapt.lk.ForallLeftRule b hyp.h_3), intros hyp.h_74,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_3), intros hyp.h_75,
apply (gapt.lk.ForallLeftRule (quotient (difference b1 b) (product (difference b1 b) b2)) hyp.h_75), intros hyp.h_76,
apply (gapt.lk.ForallLeftRule (quotient (quotient (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_75), intros hyp.h_77,
apply (gapt.lk.ForallLeftRule (quotient b1 b) hyp.h_74), intros hyp.h_78,
apply (gapt.lk.ForallLeftRule (quotient (quotient b1 b) b) hyp.h_74), intros hyp.h_79,
apply (gapt.lk.ForallLeftRule b1 hyp.h_73), intros hyp.h_80,
apply (gapt.lk.ForallLeftRule b hyp.h_73), intros hyp.h_81,
apply (gapt.lk.ForallLeftRule a1 hyp.h_4), intros hyp.h_82,
apply (gapt.lk.ForallLeftRule a hyp.h_4), intros hyp.h_83,
apply (gapt.lk.ForallLeftRule b1 hyp.h_83), intros hyp.h_84,
apply (gapt.lk.ForallLeftRule b hyp.h_83), intros hyp.h_85,
apply (gapt.lk.ForallLeftRule c1 hyp.h_85), intros hyp.h_86,
apply (gapt.lk.ForallLeftRule c hyp.h_84), intros hyp.h_87,
apply (gapt.lk.ForallLeftRule b1 hyp.h_82), intros hyp.h_88,
apply (gapt.lk.ForallLeftRule b hyp.h_82), intros hyp.h_89,
apply (gapt.lk.ForallLeftRule b2 hyp.h_82), intros hyp.h_90,
apply (gapt.lk.ForallLeftRule c1 hyp.h_90), intros hyp.h_91,
apply (gapt.lk.ForallLeftRule c hyp.h_89), intros hyp.h_92,
apply (gapt.lk.ForallLeftRule c2 hyp.h_88), intros hyp.h_93,
apply (gapt.lk.ForallLeftRule b2 hyp.h_5), intros hyp.h_94,
apply (gapt.lk.ForallLeftRule (product c b) hyp.h_5), intros hyp.h_95,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_5), intros hyp.h_96,
apply (gapt.lk.ForallLeftRule (product c b1) hyp.h_5), intros hyp.h_97,
apply (gapt.lk.ForallLeftRule c hyp.h_5), intros hyp.h_98,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_5), intros hyp.h_99,
apply (gapt.lk.ForallLeftRule b1 hyp.h_5), intros hyp.h_100,
apply (gapt.lk.ForallLeftRule b hyp.h_5), intros hyp.h_101,
apply (gapt.lk.ForallLeftRule b2 hyp.h_6), intros hyp.h_102,
apply (gapt.lk.ForallLeftRule (product c b) hyp.h_6), intros hyp.h_103,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_6), intros hyp.h_104,
apply (gapt.lk.ForallLeftRule (product c b1) hyp.h_6), intros hyp.h_105,
apply (gapt.lk.ForallLeftRule c hyp.h_6), intros hyp.h_106,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_6), intros hyp.h_107,
apply (gapt.lk.ForallLeftRule c2 hyp.h_6), intros hyp.h_108,
apply (gapt.lk.ForallLeftRule b1 hyp.h_6), intros hyp.h_109,
apply (gapt.lk.ForallLeftRule (difference c c) hyp.h_6), intros hyp.h_110,
apply (gapt.lk.ForallLeftRule b hyp.h_6), intros hyp.h_111,
apply (gapt.lk.ForallLeftRule (quotient c b) hyp.h_111), intros hyp.h_112,
apply (gapt.lk.ForallLeftRule (quotient (product b (quotient b1 b)) b) hyp.h_111), intros hyp.h_113,
apply (gapt.lk.ForallLeftRule (quotient c1 b) hyp.h_111), intros hyp.h_114,
apply (gapt.lk.ForallLeftRule (quotient b1 b) hyp.h_111), intros hyp.h_115,
apply (gapt.lk.ForallLeftRule a1 hyp.h_111), intros hyp.h_116,
apply (gapt.lk.ForallLeftRule (quotient (product b b1) b) hyp.h_111), intros hyp.h_117,
apply (gapt.lk.ForallLeftRule (quotient (quotient b1 b) b) hyp.h_111), intros hyp.h_118,
apply (gapt.lk.ForallLeftRule b hyp.h_118), intros hyp.h_119,
apply (gapt.lk.ForallLeftRule b hyp.h_119), intros hyp.h_120,
apply (gapt.lk.ForallLeftRule b hyp.h_117), intros hyp.h_121,
apply (gapt.lk.ForallLeftRule b hyp.h_121), intros hyp.h_122,
apply (gapt.lk.ForallLeftRule c hyp.h_116), intros hyp.h_123,
apply (gapt.lk.ForallLeftRule b hyp.h_123), intros hyp.h_124,
apply (gapt.lk.ForallLeftRule b hyp.h_115), intros hyp.h_125,
apply (gapt.lk.ForallLeftRule b hyp.h_125), intros hyp.h_126,
apply (gapt.lk.ForallLeftRule (difference b a1) hyp.h_114), intros hyp.h_127,
apply (gapt.lk.ForallLeftRule (quotient (product (difference b1 b) b1) b) hyp.h_114), intros hyp.h_128,
apply (gapt.lk.ForallLeftRule b hyp.h_114), intros hyp.h_129,
apply (gapt.lk.ForallLeftRule b hyp.h_129), intros hyp.h_130,
apply (gapt.lk.ForallLeftRule b hyp.h_128), intros hyp.h_131,
apply (gapt.lk.ForallLeftRule b hyp.h_127), intros hyp.h_132,
apply (gapt.lk.ForallLeftRule b hyp.h_113), intros hyp.h_133,
apply (gapt.lk.ForallLeftRule b hyp.h_133), intros hyp.h_134,
apply (gapt.lk.ForallLeftRule c hyp.h_112), intros hyp.h_135,
apply (gapt.lk.ForallLeftRule (quotient (product (difference b1 b) b1) b) hyp.h_112), intros hyp.h_136,
apply (gapt.lk.ForallLeftRule b hyp.h_112), intros hyp.h_137,
apply (gapt.lk.ForallLeftRule b hyp.h_137), intros hyp.h_138,
apply (gapt.lk.ForallLeftRule b hyp.h_136), intros hyp.h_139,
apply (gapt.lk.ForallLeftRule b hyp.h_135), intros hyp.h_140,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_110), intros hyp.h_141,
apply (gapt.lk.ForallLeftRule c hyp.h_141), intros hyp.h_142,
apply (gapt.lk.ForallLeftRule b1 hyp.h_142), intros hyp.h_143,
apply (gapt.lk.ForallLeftRule c hyp.h_109), intros hyp.h_144,
apply (gapt.lk.ForallLeftRule (quotient c b1) hyp.h_109), intros hyp.h_145,
apply (gapt.lk.ForallLeftRule (difference (quotient (difference (product b1 b) b) b) b) hyp.h_109), intros hyp.h_146,
apply (gapt.lk.ForallLeftRule (quotient c2 b1) hyp.h_109), intros hyp.h_147,
apply (gapt.lk.ForallLeftRule a1 hyp.h_109), intros hyp.h_148,
apply (gapt.lk.ForallLeftRule (quotient b b1) hyp.h_109), intros hyp.h_149,
apply (gapt.lk.ForallLeftRule b1 hyp.h_149), intros hyp.h_150,
apply (gapt.lk.ForallLeftRule b1 hyp.h_150), intros hyp.h_151,
apply (gapt.lk.ForallLeftRule c1 hyp.h_148), intros hyp.h_152,
apply (gapt.lk.ForallLeftRule b hyp.h_152), intros hyp.h_153,
apply (gapt.lk.ForallLeftRule b1 hyp.h_147), intros hyp.h_154,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_147), intros hyp.h_155,
apply (gapt.lk.ForallLeftRule b1 hyp.h_155), intros hyp.h_156,
apply (gapt.lk.ForallLeftRule b1 hyp.h_154), intros hyp.h_157,
apply (gapt.lk.ForallLeftRule b hyp.h_146), intros hyp.h_158,
apply (gapt.lk.ForallLeftRule (quotient (difference (product b1 b) b) b) hyp.h_158), intros hyp.h_159,
apply (gapt.lk.ForallLeftRule c hyp.h_145), intros hyp.h_160,
apply (gapt.lk.ForallLeftRule b1 hyp.h_145), intros hyp.h_161,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_145), intros hyp.h_162,
apply (gapt.lk.ForallLeftRule b1 hyp.h_162), intros hyp.h_163,
apply (gapt.lk.ForallLeftRule b1 hyp.h_161), intros hyp.h_164,
apply (gapt.lk.ForallLeftRule b1 hyp.h_160), intros hyp.h_165,
apply (gapt.lk.ForallLeftRule c1 hyp.h_144), intros hyp.h_166,
apply (gapt.lk.ForallLeftRule a1 hyp.h_166), intros hyp.h_167,
apply (gapt.lk.ForallLeftRule b hyp.h_108), intros hyp.h_168,
apply (gapt.lk.ForallLeftRule b1 hyp.h_168), intros hyp.h_169,
apply (gapt.lk.ForallLeftRule a hyp.h_169), intros hyp.h_170,
apply (gapt.lk.ForallLeftRule b1 hyp.h_107), intros hyp.h_171,
apply (gapt.lk.ForallLeftRule (difference (quotient (difference (product (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_107), intros hyp.h_172,
apply (gapt.lk.ForallLeftRule (quotient b2 (difference b1 b)) hyp.h_107), intros hyp.h_173,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_173), intros hyp.h_174,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_174), intros hyp.h_175,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_172), intros hyp.h_176,
apply (gapt.lk.ForallLeftRule (quotient (difference (product (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_176), intros hyp.h_177,
apply (gapt.lk.ForallLeftRule (quotient b b1) hyp.h_171), intros hyp.h_178,
apply (gapt.lk.ForallLeftRule b1 hyp.h_178), intros hyp.h_179,
apply (gapt.lk.ForallLeftRule c hyp.h_106), intros hyp.h_180,
apply (gapt.lk.ForallLeftRule b hyp.h_180), intros hyp.h_181,
apply (gapt.lk.ForallLeftRule b hyp.h_181), intros hyp.h_182,
apply (gapt.lk.ForallLeftRule (product c b1) hyp.h_105), intros hyp.h_183,
apply (gapt.lk.ForallLeftRule c hyp.h_183), intros hyp.h_184,
apply (gapt.lk.ForallLeftRule a hyp.h_184), intros hyp.h_185,
apply (gapt.lk.ForallLeftRule (quotient (product (product (difference b1 b) b2) (quotient (difference b1 b) (product (difference b1 b) b2))) (product (difference b1 b) b2)) hyp.h_104), intros hyp.h_186,
apply (gapt.lk.ForallLeftRule (quotient (product (product (difference b1 b) b2) (difference b1 b)) (product (difference b1 b) b2)) hyp.h_104), intros hyp.h_187,
apply (gapt.lk.ForallLeftRule (quotient (difference b1 b) (product (difference b1 b) b2)) hyp.h_104), intros hyp.h_188,
apply (gapt.lk.ForallLeftRule (quotient (quotient (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_104), intros hyp.h_189,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_189), intros hyp.h_190,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_190), intros hyp.h_191,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_188), intros hyp.h_192,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_192), intros hyp.h_193,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_187), intros hyp.h_194,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_194), intros hyp.h_195,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_186), intros hyp.h_196,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_196), intros hyp.h_197,
apply (gapt.lk.ForallLeftRule (product c b) hyp.h_103), intros hyp.h_198,
apply (gapt.lk.ForallLeftRule c hyp.h_198), intros hyp.h_199,
apply (gapt.lk.ForallLeftRule a1 hyp.h_199), intros hyp.h_200,
apply (gapt.lk.ForallLeftRule (difference b2 (difference b1 b)) hyp.h_102), intros hyp.h_201,
apply (gapt.lk.ForallLeftRule (quotient (difference b2 (product (difference b1 b) b2)) b2) hyp.h_102), intros hyp.h_202,
apply (gapt.lk.ForallLeftRule (quotient c1 b2) hyp.h_102), intros hyp.h_203,
apply (gapt.lk.ForallLeftRule b hyp.h_102), intros hyp.h_204,
apply (gapt.lk.ForallLeftRule (product (quotient b b1) (difference b1 b)) hyp.h_102), intros hyp.h_205,
apply (gapt.lk.ForallLeftRule (product b1 b1) hyp.h_205), intros hyp.h_206,
apply (gapt.lk.ForallLeftRule (product b1 b1) hyp.h_206), intros hyp.h_207,
apply (gapt.lk.ForallLeftRule (product b1 b1) hyp.h_204), intros hyp.h_208,
apply (gapt.lk.ForallLeftRule (product b1 (quotient b b1)) hyp.h_208), intros hyp.h_209,
apply (gapt.lk.ForallLeftRule (difference b2 (difference b1 b)) hyp.h_203), intros hyp.h_210,
apply (gapt.lk.ForallLeftRule b2 hyp.h_203), intros hyp.h_211,
apply (gapt.lk.ForallLeftRule b2 hyp.h_211), intros hyp.h_212,
apply (gapt.lk.ForallLeftRule b2 hyp.h_210), intros hyp.h_213,
apply (gapt.lk.ForallLeftRule b2 hyp.h_202), intros hyp.h_214,
apply (gapt.lk.ForallLeftRule b2 hyp.h_214), intros hyp.h_215,
apply (gapt.lk.ForallLeftRule b2 hyp.h_201), intros hyp.h_216,
apply (gapt.lk.ForallLeftRule b2 hyp.h_216), intros hyp.h_217,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_7), intros hyp.h_218,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_7), intros hyp.h_219,
apply (gapt.lk.ForallLeftRule (product b2 b) hyp.h_7), intros hyp.h_220,
apply (gapt.lk.ForallLeftRule a1 hyp.h_7), intros hyp.h_221,
apply (gapt.lk.ForallLeftRule b hyp.h_7), intros hyp.h_222,
apply (gapt.lk.ForallLeftRule b1 hyp.h_222), intros hyp.h_223,
apply (gapt.lk.ForallLeftRule (quotient (difference (product b1 b) b) b) hyp.h_222), intros hyp.h_224,
apply (gapt.lk.ForallLeftRule b hyp.h_221), intros hyp.h_225,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_220), intros hyp.h_226,
apply (gapt.lk.ForallLeftRule b2 hyp.h_219), intros hyp.h_227,
apply (gapt.lk.ForallLeftRule (quotient (difference (product (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_218), intros hyp.h_228,
apply (gapt.lk.ForallLeftRule b2 hyp.h_218), intros hyp.h_229,
apply (gapt.lk.ForallLeftRule b2 hyp.h_8), intros hyp.h_230,
apply (gapt.lk.ForallLeftRule (quotient c b) hyp.h_8), intros hyp.h_231,
apply (gapt.lk.ForallLeftRule (product c b) hyp.h_8), intros hyp.h_232,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) b2) hyp.h_8), intros hyp.h_233,
apply (gapt.lk.ForallLeftRule (product (difference (quotient (difference (product (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (difference b1 b)) hyp.h_8), intros hyp.h_234,
apply (gapt.lk.ForallLeftRule (product (difference b2 (difference b1 b)) b2) hyp.h_8), intros hyp.h_235,
apply (gapt.lk.ForallLeftRule c hyp.h_8), intros hyp.h_236,
apply (gapt.lk.ForallLeftRule (quotient (difference b2 (product (difference b1 b) b2)) b2) hyp.h_8), intros hyp.h_237,
apply (gapt.lk.ForallLeftRule (quotient (difference (difference b1 b) (product b2 b)) (difference b1 b)) hyp.h_8), intros hyp.h_238,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (product (product (difference b1 b) b2) (quotient (quotient (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)))) hyp.h_8), intros hyp.h_239,
apply (gapt.lk.ForallLeftRule (product (difference b1 b) (difference c c)) hyp.h_8), intros hyp.h_240,
apply (gapt.lk.ForallLeftRule (product b c2) hyp.h_8), intros hyp.h_241,
apply (gapt.lk.ForallLeftRule (product (difference b b) b) hyp.h_8), intros hyp.h_242,
apply (gapt.lk.ForallLeftRule (product b (product b (quotient (quotient b1 b) b))) hyp.h_8), intros hyp.h_243,
apply (gapt.lk.ForallLeftRule (product b (product b (quotient b1 b))) hyp.h_8), intros hyp.h_244,
apply (gapt.lk.ForallLeftRule (product c1 b1) hyp.h_8), intros hyp.h_245,
apply (gapt.lk.ForallLeftRule (product (product (difference b1 b) b2) (product (product (difference b1 b) b2) (quotient (difference b1 b) (product (difference b1 b) b2)))) hyp.h_8), intros hyp.h_246,
apply (gapt.lk.ForallLeftRule (product (difference (quotient (difference (product b1 b) b) b) b) b1) hyp.h_8), intros hyp.h_247,
apply (gapt.lk.ForallLeftRule b hyp.h_8), intros hyp.h_248,
apply (gapt.lk.ForallLeftRule b hyp.h_248), intros hyp.h_249,
apply (gapt.lk.ForallLeftRule (quotient (product b (product b b1)) b) hyp.h_248), intros hyp.h_250,
apply (gapt.lk.ForallLeftRule (product (quotient (difference (product b1 b) b) b) b) hyp.h_247), intros hyp.h_251,
apply (gapt.lk.ForallLeftRule (product (product (quotient (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_246), intros hyp.h_252,
apply (gapt.lk.ForallLeftRule (product a1 c) hyp.h_245), intros hyp.h_253,
apply (gapt.lk.ForallLeftRule (product (product (quotient b1 b) b) b) hyp.h_244), intros hyp.h_254,
apply (gapt.lk.ForallLeftRule (product (product (quotient (quotient b1 b) b) b) b) hyp.h_243), intros hyp.h_255,
apply (gapt.lk.ForallLeftRule a1 hyp.h_242), intros hyp.h_256,
apply (gapt.lk.ForallLeftRule (product b1 c) hyp.h_241), intros hyp.h_257,
apply (gapt.lk.ForallLeftRule (product b1 c) hyp.h_240), intros hyp.h_258,
apply (gapt.lk.ForallLeftRule (product (product (quotient (quotient (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_239), intros hyp.h_259,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_238), intros hyp.h_260,
apply (gapt.lk.ForallLeftRule b2 hyp.h_237), intros hyp.h_261,
apply (gapt.lk.ForallLeftRule c hyp.h_236), intros hyp.h_262,
apply (gapt.lk.ForallLeftRule a1 hyp.h_235), intros hyp.h_263,
apply (gapt.lk.ForallLeftRule (product (quotient (difference (product (difference b1 b) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) (product (difference b1 b) b2)) hyp.h_234), intros hyp.h_264,
apply (gapt.lk.ForallLeftRule (quotient (product (product (difference b1 b) b2) (product (product (difference b1 b) b2) (difference b1 b))) (product (difference b1 b) b2)) hyp.h_233), intros hyp.h_265,
apply (gapt.lk.ForallLeftRule (product a1 c) hyp.h_232), intros hyp.h_266,
apply (gapt.lk.ForallLeftRule b hyp.h_231), intros hyp.h_267,
apply (gapt.lk.ForallLeftRule (difference b1 b) hyp.h_230), intros hyp.h_268,
apply (gapt.lk.AndLeftRule hyp.h_93), intros hyp.h_269 hyp.h_270,
apply (gapt.lk.AndLeftRule hyp.h_92), intros hyp.h_271 hyp.h_272,
apply (gapt.lk.AndLeftRule hyp.h_91), intros hyp.h_273 hyp.h_274,
apply (gapt.lk.AndLeftRule hyp.h_87), intros hyp.h_275 hyp.h_276,
apply (gapt.lk.AndLeftRule hyp.h_86), intros hyp.h_277 hyp.h_278,
apply (gapt.lk.AndLeftRule hyp.h_48), intros hyp.h_279 hyp.h_280,
apply (gapt.lk.ImpLeftRule hyp.h_280), intros hyp.h_281,
apply (gapt.lk.ImpLeftRule hyp.h_277), intros hyp.h_282,
apply (gapt.lk.LogicalAxiom hyp.h_9 hyp.h_282), intros hyp.h_282,
apply (gapt.lk.ImpLeftRule hyp.h_275), intros hyp.h_283,
apply (gapt.lk.LogicalAxiom hyp.h_10 hyp.h_283), intros hyp.h_283,
apply (gapt.lk.ImpLeftRule hyp.h_273), intros hyp.h_284,
apply (gapt.lk.LogicalAxiom hyp.h_11 hyp.h_284), intros hyp.h_284,
apply (gapt.lk.ImpLeftRule hyp.h_271), intros hyp.h_285,
apply (gapt.lk.LogicalAxiom hyp.h_12 hyp.h_285), intros hyp.h_285,
apply (gapt.lk.ImpLeftRule hyp.h_269), intros hyp.h_286,
apply (gapt.lk.LogicalAxiom hyp.h_13 hyp.h_286), intros hyp.h_286,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference b x) = b)) b (product b b) hyp.h_101 hyp.h_249), intros hyp.h_287,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference a1 (product a1 (product x b))) = (product x b))) b (difference b b) hyp.h_287 hyp.h_256), intros hyp.h_288,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference a1 (product a1 x)) = x)) b (product b b) hyp.h_101 hyp.h_288), intros hyp.h_289,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference a1 x) = b)) (product b c) (product a1 b) hyp.h_285 hyp.h_289), intros hyp.h_290,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient x b1) = a)) (product b1 c) (product a b1) hyp.h_283 hyp.h_30), intros hyp.h_291,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b1) x) = (product (product b1 (quotient c b1)) (product b1 b1)))) c (product (quotient c b1) b1) hyp.h_61 hyp.h_164), intros hyp.h_292,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x c) = (product (product b1 (quotient c b1)) x))) b1 (product b1 b1) hyp.h_100 hyp.h_292), intros hyp.h_293,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b1) = (product b1 (quotient c b1)))) (product b1 c) (product (product b1 (quotient c b1)) b1) hyp.h_293 hyp.h_31), intros hyp.h_294,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b1 (quotient c b1)))) a (quotient (product b1 c) b1) hyp.h_291 hyp.h_294), intros hyp.h_295,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 (difference b1 b)) x) = (product (product b1 (quotient c b1)) (product (difference b1 b) b1)))) c (product (quotient c b1) b1) hyp.h_61 hyp.h_163), intros hyp.h_296,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x c) = (product (product b1 (quotient c b1)) (product (difference b1 b) b1)))) b (product b1 (difference b1 b)) hyp.h_223 hyp.h_296), intros hyp.h_297,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b c) = (product x (product (difference b1 b) b1)))) a (product b1 (quotient c b1)) hyp.h_295 hyp.h_297), intros hyp.h_298,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient x b) = a1)) (product b c) (product a1 b) hyp.h_285 hyp.h_28), intros hyp.h_299,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b b) x) = (product (product b (quotient c b)) (product b b)))) c (product (quotient c b) b) hyp.h_55 hyp.h_138), intros hyp.h_300,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x c) = (product (product b (quotient c b)) x))) b (product b b) hyp.h_101 hyp.h_300), intros hyp.h_301,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b) = (product b (quotient c b)))) (product b c) (product (product b (quotient c b)) b) hyp.h_301 hyp.h_21), intros hyp.h_302,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b (quotient c b)))) a1 (quotient (product b c) b) hyp.h_299 hyp.h_302), intros hyp.h_303,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b c) x) = (product (product b (quotient c b)) (product c b)))) c (product (quotient c b) b) hyp.h_55 hyp.h_140), intros hyp.h_304,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b c) c) = (product x (product c b)))) a1 (product b (quotient c b)) hyp.h_303 hyp.h_304), intros hyp.h_305,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product c (product c b))) = c)) (product a1 (product c b)) (product (product b c) c) hyp.h_305 hyp.h_81), intros hyp.h_306,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product a1 c) x) = (product (product a1 (product c b)) (product c (product c b))))) (product c b) (product (product c b) (product c b)) hyp.h_95 hyp.h_200), intros hyp.h_307,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product a1 c) (product c b)) = x)) c (product (product a1 (product c b)) (product c (product c b))) hyp.h_306 hyp.h_307), intros hyp.h_308,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product a1 c) x) = (product c b))) c (product (product a1 c) (product c b)) hyp.h_308 hyp.h_266), intros hyp.h_309,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b b) x) = (product (product b c) (product b c)))) c (product c c) hyp.h_98 hyp.h_182), intros hyp.h_310,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x c) = (product (product b c) (product b c)))) b (product b b) hyp.h_101 hyp.h_310), intros hyp.h_311,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b c) x) = (product (product b a1) (product c b)))) (product b c) (product a1 b) hyp.h_285 hyp.h_124), intros hyp.h_312,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, (x = (product (product b a1) (product c b)))) (product b c) (product (product b c) (product b c)) hyp.h_311 hyp.h_312), intros hyp.h_313,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b c) = (product (product b a1) x))) (difference (product a1 c) c) (product c b) hyp.h_309 hyp.h_313), intros hyp.h_314,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient x b) = a)) (product b c1) (product a b) hyp.h_282 hyp.h_23), intros hyp.h_315,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient c1 b) b)) = (product (product b (quotient c1 b)) x))) b (product b b) hyp.h_101 hyp.h_130), intros hyp.h_316,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b x) = (product (product b (quotient c1 b)) b))) c1 (product (quotient c1 b) b) hyp.h_56 hyp.h_316), intros hyp.h_317,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b) = (product b (quotient c1 b)))) (product b c1) (product (product b (quotient c1 b)) b) hyp.h_317 hyp.h_25), intros hyp.h_318,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b (quotient c1 b)))) a (quotient (product b c1) b) hyp.h_315 hyp.h_318), intros hyp.h_319,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference b x) = (quotient c b))) a1 (product b (quotient c b)) hyp.h_303 hyp.h_267), intros hyp.h_320,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x b) = c)) (difference b a1) (quotient c b) hyp.h_320 hyp.h_55), intros hyp.h_321,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b (difference b a1)) (product (quotient c1 b) b)) = (product (product b (quotient c1 b)) x))) c (product (difference b a1) b) hyp.h_321 hyp.h_132), intros hyp.h_322,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient c1 b) b)) = (product (product b (quotient c1 b)) c))) a1 (product b (difference b a1)) hyp.h_225 hyp.h_322), intros hyp.h_323,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product a1 (product (quotient c1 b) b)) = (product x c))) a (product b (quotient c1 b)) hyp.h_319 hyp.h_323), intros hyp.h_324,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product a1 x) = (product a c))) c1 (product (quotient c1 b) b) hyp.h_56 hyp.h_324), intros hyp.h_325,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 c) x) = (product (product b1 (quotient c b1)) (product c b1)))) c (product (quotient c b1) b1) hyp.h_61 hyp.h_165), intros hyp.h_326,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b1 c) c) = (product x (product c b1)))) a (product b1 (quotient c b1)) hyp.h_295 hyp.h_326), intros hyp.h_327,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product c (product c b1))) = c)) (product a (product c b1)) (product (product b1 c) c) hyp.h_327 hyp.h_80), intros hyp.h_328,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product a c) (product (product c b1) (product c b1))) = x)) c (product (product a (product c b1)) (product c (product c b1))) hyp.h_328 hyp.h_185), intros hyp.h_329,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product a c) x) = c)) (product c b1) (product (product c b1) (product c b1)) hyp.h_97 hyp.h_329), intros hyp.h_330,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x (product c b1)) = c)) (product a1 c1) (product a c) hyp.h_325 hyp.h_330), intros hyp.h_331,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product a1 c) x) = (product c1 b1))) (product (product a1 c1) (product c b1)) (product (product a1 c) (product c1 b1)) hyp.h_167 hyp.h_253), intros hyp.h_332,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product a1 c) x) = (product c1 b1))) c (product (product a1 c1) (product c b1)) hyp.h_331 hyp.h_332), intros hyp.h_333,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product b c2)) = (product (product a b) (product b1 c2)))) (product b1 c) (product a b1) hyp.h_283 hyp.h_170), intros hyp.h_334,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b1 c) (product b c2)) = (product (product a b) x))) (product a1 b1) (product b1 c2) hyp.h_286 hyp.h_334), intros hyp.h_335,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 c) (product b c2)) = (product x (product a1 b1)))) (product b c1) (product a b) hyp.h_282 hyp.h_335), intros hyp.h_336,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product b1 c) x) = (product b c2))) (product (product b c1) (product a1 b1)) (product (product b1 c) (product b c2)) hyp.h_336 hyp.h_257), intros hyp.h_337,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product b1 c) x) = (product b c2))) (product (product b a1) (product c1 b1)) (product (product b c1) (product a1 b1)) hyp.h_153 hyp.h_337), intros hyp.h_338,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product b1 c) (product (product b a1) x)) = (product b c2))) (difference (product a1 c) c) (product c1 b1) hyp.h_333 hyp.h_338), intros hyp.h_339,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product b1 c) x) = (product b c2))) (product b c) (product (product b a1) (difference (product a1 c) c)) hyp.h_314 hyp.h_339), intros hyp.h_340,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference c x) = c)) c (product c c) hyp.h_98 hyp.h_262), intros hyp.h_341,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 c) (product (difference b1 b) x)) = (product (product b1 (difference b1 b)) (product c x)))) c (difference c c) hyp.h_341 hyp.h_143), intros hyp.h_342,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 c) (product (difference b1 b) c)) = (product x (product c c)))) b (product b1 (difference b1 b)) hyp.h_223 hyp.h_342), intros hyp.h_343,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 c) (product (difference b1 b) c)) = (product b x))) c (product c c) hyp.h_98 hyp.h_343), intros hyp.h_344,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product b1 c) (product (product b1 c) (product (difference b1 b) x))) = (product (difference b1 b) x))) c (difference c c) hyp.h_341 hyp.h_258), intros hyp.h_345,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product b1 c) x) = (product (difference b1 b) c))) (product b c) (product (product b1 c) (product (difference b1 b) c)) hyp.h_344 hyp.h_345), intros hyp.h_346,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x c) = (difference b1 b))) (difference (product b1 c) (product b c)) (product (difference b1 b) c) hyp.h_346 hyp.h_37), intros hyp.h_347,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient x c) = (difference b1 b))) (product b c2) (difference (product b1 c) (product b c)) hyp.h_340 hyp.h_347), intros hyp.h_348,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b1) x) = (product (product b1 (quotient c2 b1)) (product b1 b1)))) c2 (product (quotient c2 b1) b1) hyp.h_62 hyp.h_157), intros hyp.h_349,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x c2) = (product (product b1 (quotient c2 b1)) x))) b1 (product b1 b1) hyp.h_100 hyp.h_349), intros hyp.h_350,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, (x = (product (product b1 (quotient c2 b1)) b1))) (product a1 b1) (product b1 c2) hyp.h_286 hyp.h_350), intros hyp.h_351,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b1) = (product b1 (quotient c2 b1)))) (product a1 b1) (product (product b1 (quotient c2 b1)) b1) hyp.h_351 hyp.h_29), intros hyp.h_352,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b1 (quotient c2 b1)))) a1 (quotient (product a1 b1) b1) hyp.h_32 hyp.h_352), intros hyp.h_353,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 (difference b1 b)) x) = (product (product b1 (quotient c2 b1)) (product (difference b1 b) b1)))) c2 (product (quotient c2 b1) b1) hyp.h_62 hyp.h_156), intros hyp.h_354,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x c2) = (product (product b1 (quotient c2 b1)) (product (difference b1 b) b1)))) b (product b1 (difference b1 b)) hyp.h_223 hyp.h_354), intros hyp.h_355,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b c2) = (product x (product (difference b1 b) b1)))) a1 (product b1 (quotient c2 b1)) hyp.h_353 hyp.h_355), intros hyp.h_356,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b (quotient (product (difference b1 b) b1) b)) (product (quotient c b) b)) = (product (product b (quotient c b)) x))) (product (difference b1 b) b1) (product (quotient (product (difference b1 b) b1) b) b) hyp.h_59 hyp.h_139), intros hyp.h_357,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b (quotient (product (difference b1 b) b1) b)) (product x b)) = (product (product b x) (product (difference b1 b) b1)))) (difference b a1) (quotient c b) hyp.h_320 hyp.h_357), intros hyp.h_358,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b (quotient (product (difference b1 b) b1) b)) x) = (product (product b (difference b a1)) (product (difference b1 b) b1)))) c (product (difference b a1) b) hyp.h_321 hyp.h_358), intros hyp.h_359,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b (quotient (product (difference b1 b) b1) b)) c) = (product x (product (difference b1 b) b1)))) a1 (product b (difference b a1)) hyp.h_225 hyp.h_359), intros hyp.h_360,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b (quotient (product (difference b1 b) b1) b)) c) = x)) (product b c2) (product a1 (product (difference b1 b) b1)) hyp.h_356 hyp.h_360), intros hyp.h_361,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient x c) = (product b (quotient (product (difference b1 b) b1) b)))) (product b c2) (product (product b (quotient (product (difference b1 b) b1) b)) c) hyp.h_361 hyp.h_36), intros hyp.h_362,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b (quotient (product (difference b1 b) b1) b)))) (difference b1 b) (quotient (product b c2) c) hyp.h_348 hyp.h_362), intros hyp.h_363,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b (quotient (product (difference b1 b) b1) b)) (product (quotient c1 b) b)) = (product x (product (quotient (product (difference b1 b) b1) b) b)))) a (product b (quotient c1 b)) hyp.h_319 hyp.h_131), intros hyp.h_364,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x (product (quotient c1 b) b)) = (product a (product (quotient (product (difference b1 b) b1) b) b)))) (difference b1 b) (product b (quotient (product (difference b1 b) b1) b)) hyp.h_363 hyp.h_364), intros hyp.h_365,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (difference b1 b) (product (quotient c1 b) b)) = (product a x))) (product (difference b1 b) b1) (product (quotient (product (difference b1 b) b1) b) b) hyp.h_59 hyp.h_365), intros hyp.h_366,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (difference b1 b) (product (quotient c1 b) b)) = x)) (product b c) (product a (product (difference b1 b) b1)) hyp.h_298 hyp.h_366), intros hyp.h_367,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (difference b1 b) x) = (product b c))) c1 (product (quotient c1 b) b) hyp.h_56 hyp.h_367), intros hyp.h_368,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient c1 b2) b2)) = (product (product b2 (quotient c1 b2)) x))) b2 (product b2 b2) hyp.h_94 hyp.h_212), intros hyp.h_369,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b2 x) = (product (product b2 (quotient c1 b2)) b2))) c1 (product (quotient c1 b2) b2) hyp.h_72 hyp.h_369), intros hyp.h_370,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, (x = (product (product b2 (quotient c1 b2)) b2))) (product a1 b2) (product b2 c1) hyp.h_284 hyp.h_370), intros hyp.h_371,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b2) = (product b2 (quotient c1 b2)))) (product a1 b2) (product (product b2 (quotient c1 b2)) b2) hyp.h_371 hyp.h_44), intros hyp.h_372,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b2 (quotient c1 b2)))) a1 (quotient (product a1 b2) b2) hyp.h_45 hyp.h_372), intros hyp.h_373,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b2 (difference b2 (difference b1 b))) (product (quotient c1 b2) b2)) = (product x (product (difference b2 (difference b1 b)) b2)))) a1 (product b2 (quotient c1 b2)) hyp.h_373 hyp.h_213), intros hyp.h_374,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient c1 b2) b2)) = (product a1 (product (difference b2 (difference b1 b)) b2)))) (difference b1 b) (product b2 (difference b2 (difference b1 b))) hyp.h_227 hyp.h_374), intros hyp.h_375,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (difference b1 b) x) = (product a1 (product (difference b2 (difference b1 b)) b2)))) c1 (product (quotient c1 b2) b2) hyp.h_72 hyp.h_375), intros hyp.h_376,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference a1 x) = (product (difference b2 (difference b1 b)) b2))) (product (difference b1 b) c1) (product a1 (product (difference b2 (difference b1 b)) b2)) hyp.h_376 hyp.h_263), intros hyp.h_377,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 b2) (product (difference b2 (difference b1 b)) b2)) = (product x (product b2 b2)))) (difference b1 b) (product b2 (difference b2 (difference b1 b))) hyp.h_227 hyp.h_217), intros hyp.h_378,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (difference b2 (difference b1 b)) b2)) = (product (difference b1 b) x))) b2 (product b2 b2) hyp.h_94 hyp.h_378), intros hyp.h_379,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b2 x) = (product (difference b1 b) b2))) (difference a1 (product (difference b1 b) c1)) (product (difference b2 (difference b1 b)) b2) hyp.h_377 hyp.h_379), intros hyp.h_380,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b2) = (difference b1 b))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_43), intros hyp.h_381,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b2 (difference b2 x)) = x)) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_229), intros hyp.h_382,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (quotient (difference b2 x) b2) b2) = (difference b2 x))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_71), intros hyp.h_383,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient (difference b2 (product (difference b1 b) b2)) b2) b2)) = (product (product b2 (quotient (difference b2 (product (difference b1 b) b2)) b2)) x))) b2 (product b2 b2) hyp.h_94 hyp.h_215), intros hyp.h_384,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b2 (product (quotient (difference b2 x) b2) b2)) = (product (product b2 (quotient (difference b2 x) b2)) b2))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_384), intros hyp.h_385,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b2 x) = (product (product b2 (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2)) b2))) (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) (product (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2) b2) hyp.h_383 hyp.h_385), intros hyp.h_386,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product (product b2 (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2)) b2))) (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference b2 (product b2 (difference a1 (product (difference b1 b) c1))))) hyp.h_382 hyp.h_386), intros hyp.h_387,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient (product (product b2 (quotient (difference b2 x) b2)) b2) b2) = (product b2 (quotient (difference b2 x) b2)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_42), intros hyp.h_388,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b2) = (product b2 (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2)) b2) hyp.h_387 hyp.h_388), intros hyp.h_389,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product b2 (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2)))) (difference b1 b) (quotient (product b2 (difference a1 (product (difference b1 b) c1))) b2) hyp.h_381 hyp.h_389), intros hyp.h_390,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference b2 (product b2 (quotient (difference b2 x) b2))) = (quotient (difference b2 x) b2))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_261), intros hyp.h_391,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference b2 x) = (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2))) (difference b1 b) (product b2 (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2)) hyp.h_390 hyp.h_391), intros hyp.h_392,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x b2) = (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))))) (difference b2 (difference b1 b)) (quotient (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))) b2) hyp.h_392 hyp.h_383), intros hyp.h_393,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, (x = (difference b2 (product b2 (difference a1 (product (difference b1 b) c1)))))) (difference a1 (product (difference b1 b) c1)) (product (difference b2 (difference b1 b)) b2) hyp.h_377 hyp.h_393), intros hyp.h_394,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference a1 x) = (difference b2 (product b2 (difference a1 x))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_394), intros hyp.h_395,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (difference b2 (product b2 x)))) b (difference a1 (product b c)) hyp.h_290 hyp.h_395), intros hyp.h_396,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (difference b1 b) x) = b2)) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_268), intros hyp.h_397,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (difference b1 b) (product b2 (difference a1 x))) = b2)) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_397), intros hyp.h_398,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (difference b1 b) (product b2 x)) = b2)) b (difference a1 (product b c)) hyp.h_290 hyp.h_398), intros hyp.h_399,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (difference b1 b) x) = (product b2 b))) b2 (difference (difference b1 b) (product b2 b)) hyp.h_399 hyp.h_226), intros hyp.h_400,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (difference (difference (difference b1 b) x) x) (difference b1 b)) (difference b1 b)) = (difference (difference (difference b1 b) x) x))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_34), intros hyp.h_401,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (difference x (product b2 b)) (difference b1 b)) (difference b1 b)) = (difference x (product b2 b)))) b2 (difference (difference b1 b) (product b2 b)) hyp.h_399 hyp.h_401), intros hyp.h_402,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient (product x (difference b1 b)) (difference b1 b)) = x)) b (difference b2 (product b2 b)) hyp.h_396 hyp.h_402), intros hyp.h_403,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (quotient (difference b1 b) x) x) = (difference b1 b))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_65), intros hyp.h_404,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))) = (difference b1 b))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_404), intros hyp.h_405,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (difference b1 b) (product b2 x)) (product b2 x)) = (difference b1 b))) b (difference a1 (product b c)) hyp.h_290 hyp.h_405), intros hyp.h_406,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (quotient (difference b1 b) x) x) x) = (quotient (difference b1 b) x))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_70), intros hyp.h_407,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product (product (quotient (quotient (difference b1 b) x) x) x) x) (product x (product x (quotient (quotient (difference b1 b) x) x)))) = x)) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_77), intros hyp.h_408,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product x (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))))) = (product b2 b))) (quotient (difference b1 b) (product b2 b)) (product (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) hyp.h_407 hyp.h_408), intros hyp.h_409,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))))) = (product b2 b))) (difference b1 b) (product (quotient (difference b1 b) (product b2 b)) (product b2 b)) hyp.h_406 hyp.h_409), intros hyp.h_410,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product (product (quotient (quotient (difference b1 b) x) x) x) x) (product (product (product (quotient (quotient (difference b1 b) x) x) x) x) (product x (product x (quotient (quotient (difference b1 b) x) x))))) = (product x (product x (quotient (quotient (difference b1 b) x) x))))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_259), intros hyp.h_411,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (product (quotient (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product (product (product (quotient (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (quotient (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))))))) = (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (quotient (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_411), intros hyp.h_412,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (product (quotient (quotient (difference b1 b) (product b2 x)) (product b2 x)) (product b2 x)) (product b2 x)) (product (product (product (quotient (quotient (difference b1 b) (product b2 x)) (product b2 x)) (product b2 x)) (product b2 x)) (product (product b2 x) (product (product b2 x) (quotient (quotient (difference b1 b) (product b2 x)) (product b2 x)))))) = (product (product b2 x) (product (product b2 x) (quotient (quotient (difference b1 b) (product b2 x)) (product b2 x)))))) b (difference a1 (product b c)) hyp.h_290 hyp.h_412), intros hyp.h_413,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product x (product b2 b)) (product (product x (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))))) = (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))))) (quotient (difference b1 b) (product b2 b)) (product (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) hyp.h_407 hyp.h_413), intros hyp.h_414,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference x (product x (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))))) = (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))))) (difference b1 b) (product (quotient (difference b1 b) (product b2 b)) (product b2 b)) hyp.h_406 hyp.h_414), intros hyp.h_415,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (difference b1 b) x) = (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))))) (product b2 b) (product (difference b1 b) (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))))) hyp.h_410 hyp.h_415), intros hyp.h_416,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))))) b2 (difference (difference b1 b) (product b2 b)) hyp.h_399 hyp.h_416), intros hyp.h_417,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x x) = x)) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_96), intros hyp.h_418,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product x x) (product (quotient (quotient (difference b1 b) x) x) x)) = (product (product x (quotient (quotient (difference b1 b) x) x)) (product x x)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_191), intros hyp.h_419,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1))))) = (product (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1))))) x))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference a1 (product (difference b1 b) c1)))) hyp.h_418 hyp.h_419), intros hyp.h_420,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 (difference a1 x)) (product (quotient (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x)))) = (product (product (product b2 (difference a1 x)) (quotient (quotient (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x)))) (product b2 (difference a1 x))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_420), intros hyp.h_421,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 x) (product (quotient (quotient (difference b1 b) (product b2 x)) (product b2 x)) (product b2 x))) = (product (product (product b2 x) (quotient (quotient (difference b1 b) (product b2 x)) (product b2 x))) (product b2 x)))) b (difference a1 (product b c)) hyp.h_290 hyp.h_421), intros hyp.h_422,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 b) x) = (product (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))) (product b2 b)))) (quotient (difference b1 b) (product b2 b)) (product (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) hyp.h_407 hyp.h_422), intros hyp.h_423,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product x (quotient (quotient (difference b1 b) x) x)) x) x) = (product x (quotient (quotient (difference b1 b) x) x)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_38), intros hyp.h_424,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x (product b2 b)) = (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))))) (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))) (product b2 b)) hyp.h_423 hyp.h_424), intros hyp.h_425,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product x (quotient (product x (quotient (difference b1 b) x)) x)) x) x) = (product x (quotient (product x (quotient (difference b1 b) x)) x)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_39), intros hyp.h_426,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product (product b2 b) x) (product b2 b)) (product b2 b)) = (product (product b2 b) x))) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))) (quotient (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product b2 b)) hyp.h_425 hyp.h_426), intros hyp.h_427,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient (product x (product b2 b)) (product b2 b)) = x)) b2 (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))) hyp.h_417 hyp.h_427), intros hyp.h_428,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product (product (quotient (difference b1 b) x) x) x) (product x (product x (quotient (difference b1 b) x)))) = x)) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_76), intros hyp.h_429,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product x (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (difference b1 b) (product b2 b))))) = (product b2 b))) (difference b1 b) (product (quotient (difference b1 b) (product b2 b)) (product b2 b)) hyp.h_406 hyp.h_429), intros hyp.h_430,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product (product (quotient (difference b1 b) x) x) x) (product (product (product (quotient (difference b1 b) x) x) x) (product x (product x (quotient (difference b1 b) x))))) = (product x (product x (quotient (difference b1 b) x))))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_252), intros hyp.h_431,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product x (product b2 (difference a1 (product (difference b1 b) c1)))) (product (product x (product b2 (difference a1 (product (difference b1 b) c1)))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))))))) = (product (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))))))) (difference b1 b) (product (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) hyp.h_404 hyp.h_431), intros hyp.h_432,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (difference b1 b) (product b2 (difference a1 x))) (product (product (difference b1 b) (product b2 (difference a1 x))) (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (quotient (difference b1 b) (product b2 (difference a1 x))))))) = (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (quotient (difference b1 b) (product b2 (difference a1 x))))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_432), intros hyp.h_433,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (difference b1 b) (product b2 x)) (product (product (difference b1 b) (product b2 x)) (product (product b2 x) (product (product b2 x) (quotient (difference b1 b) (product b2 x)))))) = (product (product b2 x) (product (product b2 x) (quotient (difference b1 b) (product b2 x)))))) b (difference a1 (product b c)) hyp.h_290 hyp.h_433), intros hyp.h_434,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (difference b1 b) (product b2 b)) x) = (product (product b2 b) (product (product b2 b) (quotient (difference b1 b) (product b2 b)))))) (product b2 b) (product (product (difference b1 b) (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (difference b1 b) (product b2 b))))) hyp.h_430 hyp.h_434), intros hyp.h_435,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (product x (quotient (difference b1 b) x)) x) x) = (product x (quotient (difference b1 b) x)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_68), intros hyp.h_436,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product x x) (product (quotient (product x (quotient (difference b1 b) x)) x) x)) = (product (product x (quotient (product x (quotient (difference b1 b) x)) x)) (product x x)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_197), intros hyp.h_437,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1))))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1))))) = (product (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1))))) (product b2 (difference a1 (product (difference b1 b) c1))))) x))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference a1 (product (difference b1 b) c1)))) hyp.h_418 hyp.h_437), intros hyp.h_438,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 (difference a1 x)) (product (quotient (product (product b2 (difference a1 x)) (quotient (difference b1 b) (product b2 (difference a1 x)))) (product b2 (difference a1 x))) (product b2 (difference a1 x)))) = (product (product (product b2 (difference a1 x)) (quotient (product (product b2 (difference a1 x)) (quotient (difference b1 b) (product b2 (difference a1 x)))) (product b2 (difference a1 x)))) (product b2 (difference a1 x))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_438), intros hyp.h_439,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 x) (product (quotient (product (product b2 x) (quotient (difference b1 b) (product b2 x))) (product b2 x)) (product b2 x))) = (product (product (product b2 x) (quotient (product (product b2 x) (quotient (difference b1 b) (product b2 x))) (product b2 x))) (product b2 x)))) b (difference a1 (product b c)) hyp.h_290 hyp.h_439), intros hyp.h_440,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 b) x) = (product (product (product b2 b) (quotient (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product b2 b))) (product b2 b)))) (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product (quotient (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product b2 b)) (product b2 b)) hyp.h_436 hyp.h_440), intros hyp.h_441,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, (x = (product (product (product b2 b) (quotient (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product b2 b))) (product b2 b)))) (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (difference b1 b) (product b2 b)))) hyp.h_435 hyp.h_441), intros hyp.h_442,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (difference b1 b) (product b2 b)) (product b2 b)) = (product (product (product b2 b) x) (product b2 b)))) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b))) (quotient (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product b2 b)) hyp.h_425 hyp.h_442), intros hyp.h_443,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product (difference b1 b) (product b2 b)) (product b2 b)) = (product x (product b2 b)))) b2 (product (product b2 b) (product (product b2 b) (quotient (quotient (difference b1 b) (product b2 b)) (product b2 b)))) hyp.h_417 hyp.h_443), intros hyp.h_444,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product x x) (product (quotient (difference b1 b) x) x)) = (product (product x (quotient (difference b1 b) x)) (product x x)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_193), intros hyp.h_445,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference a1 (product (difference b1 b) c1)))) x) = (product (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1))))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference a1 (product (difference b1 b) c1))))))) (difference b1 b) (product (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) hyp.h_404 hyp.h_445), intros hyp.h_446,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (difference b1 b)) = (product (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1))))) x))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference a1 (product (difference b1 b) c1)))) hyp.h_418 hyp.h_446), intros hyp.h_447,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 (difference a1 x)) (difference b1 b)) = (product (product (product b2 (difference a1 x)) (quotient (difference b1 b) (product b2 (difference a1 x)))) (product b2 (difference a1 x))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_447), intros hyp.h_448,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 x) (difference b1 b)) = (product (product (product b2 x) (quotient (difference b1 b) (product b2 x))) (product b2 x)))) b (difference a1 (product b c)) hyp.h_290 hyp.h_448), intros hyp.h_449,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product x (quotient (difference b1 b) x)) x) x) = (product x (quotient (difference b1 b) x)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_41), intros hyp.h_450,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x (product b2 b)) = (product (product b2 b) (quotient (difference b1 b) (product b2 b))))) (product (product b2 b) (difference b1 b)) (product (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (product b2 b)) hyp.h_449 hyp.h_450), intros hyp.h_451,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (product x (difference b1 b)) x) x) = (product x (difference b1 b)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_66), intros hyp.h_452,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product x x) (product (quotient (product x (difference b1 b)) x) x)) = (product (product x (quotient (product x (difference b1 b)) x)) (product x x)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_195), intros hyp.h_453,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient (product (product b2 (difference a1 (product (difference b1 b) c1))) (difference b1 b)) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1))))) = (product (product (product b2 (difference a1 (product (difference b1 b) c1))) (quotient (product (product b2 (difference a1 (product (difference b1 b) c1))) (difference b1 b)) (product b2 (difference a1 (product (difference b1 b) c1))))) x))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product b2 (difference a1 (product (difference b1 b) c1)))) hyp.h_418 hyp.h_453), intros hyp.h_454,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 (difference a1 x)) (product (quotient (product (product b2 (difference a1 x)) (difference b1 b)) (product b2 (difference a1 x))) (product b2 (difference a1 x)))) = (product (product (product b2 (difference a1 x)) (quotient (product (product b2 (difference a1 x)) (difference b1 b)) (product b2 (difference a1 x)))) (product b2 (difference a1 x))))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_454), intros hyp.h_455,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 x) (product (quotient (product (product b2 x) (difference b1 b)) (product b2 x)) (product b2 x))) = (product (product (product b2 x) (quotient (product (product b2 x) (difference b1 b)) (product b2 x))) (product b2 x)))) b (difference a1 (product b c)) hyp.h_290 hyp.h_455), intros hyp.h_456,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 b) x) = (product (product (product b2 b) (quotient (product (product b2 b) (difference b1 b)) (product b2 b))) (product b2 b)))) (product (product b2 b) (difference b1 b)) (product (quotient (product (product b2 b) (difference b1 b)) (product b2 b)) (product b2 b)) hyp.h_452 hyp.h_456), intros hyp.h_457,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b2 b) (product (product b2 b) (difference b1 b))) = (product (product (product b2 b) x) (product b2 b)))) (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (quotient (product (product b2 b) (difference b1 b)) (product b2 b)) hyp.h_451 hyp.h_457), intros hyp.h_458,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b2 b) (product (product b2 b) (difference b1 b))) = (product x (product b2 b)))) (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (difference b1 b) (product b2 b)))) hyp.h_435 hyp.h_458), intros hyp.h_459,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product x (quotient (product x (difference b1 b)) x)) x) x) = (product x (quotient (product x (difference b1 b)) x)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_40), intros hyp.h_460,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product (product b2 b) x) (product b2 b)) (product b2 b)) = (product (product b2 b) x))) (product (product b2 b) (quotient (difference b1 b) (product b2 b))) (quotient (product (product b2 b) (difference b1 b)) (product b2 b)) hyp.h_451 hyp.h_460), intros hyp.h_461,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient (product x (product b2 b)) (product b2 b)) = x)) (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product (product b2 b) (product (product b2 b) (quotient (difference b1 b) (product b2 b)))) hyp.h_435 hyp.h_461), intros hyp.h_462,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x (product b2 b)) = (difference (product (difference b1 b) (product b2 b)) (product b2 b)))) (product (product b2 b) (product (product b2 b) (difference b1 b))) (product (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) hyp.h_459 hyp.h_462), intros hyp.h_463,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (product x (product x (difference b1 b))) x) x) = (product x (product x (difference b1 b))))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_69), intros hyp.h_464,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (quotient (product x (product x (difference b1 b))) x) (product (quotient (product x (product x (difference b1 b))) x) x)) = x)) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_265), intros hyp.h_465,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (quotient (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (difference b1 b))) (product b2 (difference a1 x))) (product (quotient (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (difference b1 b))) (product b2 (difference a1 x))) (product b2 (difference a1 x)))) = (product b2 (difference a1 x)))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_465), intros hyp.h_466,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (quotient (product (product b2 x) (product (product b2 x) (difference b1 b))) (product b2 x)) (product (quotient (product (product b2 x) (product (product b2 x) (difference b1 b))) (product b2 x)) (product b2 x))) = (product b2 x))) b (difference a1 (product b c)) hyp.h_290 hyp.h_466), intros hyp.h_467,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (quotient (product (product b2 b) (product (product b2 b) (difference b1 b))) (product b2 b)) x) = (product b2 b))) (product (product b2 b) (product (product b2 b) (difference b1 b))) (product (quotient (product (product b2 b) (product (product b2 b) (difference b1 b))) (product b2 b)) (product b2 b)) hyp.h_464 hyp.h_467), intros hyp.h_468,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference x (product (product b2 b) (product (product b2 b) (difference b1 b)))) = (product b2 b))) (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (quotient (product (product b2 b) (product (product b2 b) (difference b1 b))) (product b2 b)) hyp.h_463 hyp.h_468), intros hyp.h_469,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (quotient (difference (product (difference b1 b) x) x) x) x) = (difference (product (difference b1 b) x) x))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_67), intros hyp.h_470,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (quotient (difference (product (difference b1 b) x) x) x) (difference (quotient (difference (product (difference b1 b) x) x) x) x)) = x)) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_228), intros hyp.h_471,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product (quotient (difference (product (difference b1 b) x) x) x) x) (product (difference (quotient (difference (product (difference b1 b) x) x) x) x) (difference b1 b))) = (product (product (quotient (difference (product (difference b1 b) x) x) x) (difference (quotient (difference (product (difference b1 b) x) x) x) x)) (product x (difference b1 b))))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_177), intros hyp.h_472,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product (difference (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (difference b1 b))) = (product x (product (product b2 (difference a1 (product (difference b1 b) c1))) (difference b1 b))))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (difference (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1))))) hyp.h_471 hyp.h_472), intros hyp.h_473,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (product (quotient (difference (product (difference b1 b) x) x) x) x) (product (product (quotient (difference (product (difference b1 b) x) x) x) x) (product (difference (quotient (difference (product (difference b1 b) x) x) x) x) (difference b1 b)))) = (product (difference (quotient (difference (product (difference b1 b) x) x) x) x) (difference b1 b)))) (product b2 (difference a1 (product (difference b1 b) c1))) (product (difference b1 b) b2) hyp.h_380 hyp.h_264), intros hyp.h_474,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) x) = (product (difference (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (difference b1 b)))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (product (product b2 (difference a1 (product (difference b1 b) c1))) (difference b1 b))) (product (product (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product (difference (quotient (difference (product (difference b1 b) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (product b2 (difference a1 (product (difference b1 b) c1)))) (difference b1 b))) hyp.h_473 hyp.h_474), intros hyp.h_475,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (quotient (difference (product (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product (product b2 (difference a1 x)) (product (product b2 (difference a1 x)) (difference b1 b)))) = (product (difference (quotient (difference (product (difference b1 b) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (product b2 (difference a1 x))) (difference b1 b)))) (product b c) (product (difference b1 b) c1) hyp.h_368 hyp.h_475), intros hyp.h_476,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product (quotient (difference (product (difference b1 b) (product b2 x)) (product b2 x)) (product b2 x)) (product b2 x)) (product (product b2 x) (product (product b2 x) (difference b1 b)))) = (product (difference (quotient (difference (product (difference b1 b) (product b2 x)) (product b2 x)) (product b2 x)) (product b2 x)) (difference b1 b)))) b (difference a1 (product b c)) hyp.h_290 hyp.h_476), intros hyp.h_477,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference x (product (product b2 b) (product (product b2 b) (difference b1 b)))) = (product (difference (quotient (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) (product b2 b)) (difference b1 b)))) (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product (quotient (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) (product b2 b)) hyp.h_470 hyp.h_477), intros hyp.h_478,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product (difference (quotient (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product b2 b)) (product b2 b)) (difference b1 b)))) (product b2 b) (difference (difference (product (difference b1 b) (product b2 b)) (product b2 b)) (product (product b2 b) (product (product b2 b) (difference b1 b)))) hyp.h_469 hyp.h_478), intros hyp.h_479,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b2 b) = (product (difference (quotient x (product b2 b)) (product b2 b)) (difference b1 b)))) (product b2 (product b2 b)) (difference (product (difference b1 b) (product b2 b)) (product b2 b)) hyp.h_444 hyp.h_479), intros hyp.h_480,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b2 b) = (product (difference x (product b2 b)) (difference b1 b)))) b2 (quotient (product b2 (product b2 b)) (product b2 b)) hyp.h_428 hyp.h_480), intros hyp.h_481,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b2 b) = (product x (difference b1 b)))) b (difference b2 (product b2 b)) hyp.h_396 hyp.h_481), intros hyp.h_482,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient b2 (difference b1 b)) (difference b1 b))) = (product (product (difference b1 b) (quotient b2 (difference b1 b))) x))) (difference b1 b) (product (difference b1 b) (difference b1 b)) hyp.h_99 hyp.h_175), intros hyp.h_483,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (difference b1 b) x) = (product (product (difference b1 b) (quotient b2 (difference b1 b))) (difference b1 b)))) b2 (product (quotient b2 (difference b1 b)) (difference b1 b)) hyp.h_64 hyp.h_483), intros hyp.h_484,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product (product (difference b1 b) (quotient b2 (difference b1 b))) (difference b1 b)))) (product b2 b) (product (difference b1 b) b2) hyp.h_400 hyp.h_484), intros hyp.h_485,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x (difference b1 b)) = (product (difference b1 b) (quotient b2 (difference b1 b))))) (product b2 b) (product (product (difference b1 b) (quotient b2 (difference b1 b))) (difference b1 b)) hyp.h_485 hyp.h_35), intros hyp.h_486,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient x (difference b1 b)) = (product (difference b1 b) (quotient b2 (difference b1 b))))) (product b (difference b1 b)) (product b2 b) hyp.h_482 hyp.h_486), intros hyp.h_487,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product (difference b1 b) (quotient b2 (difference b1 b))))) b (quotient (product b (difference b1 b)) (difference b1 b)) hyp.h_403 hyp.h_487), intros hyp.h_488,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (difference b1 b) (product (difference b1 b) (quotient x (difference b1 b)))) = (quotient x (difference b1 b)))) b2 (difference (difference b1 b) (product b2 b)) hyp.h_399 hyp.h_260), intros hyp.h_489,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((difference (difference b1 b) x) = (quotient b2 (difference b1 b)))) b (product (difference b1 b) (quotient b2 (difference b1 b))) hyp.h_488 hyp.h_489), intros hyp.h_490,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x (difference b1 b)) = b2)) (difference (difference b1 b) b) (quotient b2 (difference b1 b)) hyp.h_490 hyp.h_64), intros hyp.h_491,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient b1 b) b)) = (product (product b (quotient b1 b)) x))) b (product b b) hyp.h_101 hyp.h_126), intros hyp.h_492,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b x) = (product (product b (quotient b1 b)) b))) b1 (product (quotient b1 b) b) hyp.h_57 hyp.h_492), intros hyp.h_493,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product x b) (product b (product b (quotient b1 b)))) = b)) b1 (product (quotient b1 b) b) hyp.h_57 hyp.h_78), intros hyp.h_494,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product x b) (product (product x b) (product b (product b (quotient b1 b))))) = (product b (product b (quotient b1 b))))) b1 (product (quotient b1 b) b) hyp.h_57 hyp.h_254), intros hyp.h_495,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product b1 b) x) = (product b (product b (quotient b1 b))))) b (product (product b1 b) (product b (product b (quotient b1 b)))) hyp.h_494 hyp.h_495), intros hyp.h_496,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b) = (product b (quotient b1 b)))) (product b b1) (product (product b (quotient b1 b)) b) hyp.h_493 hyp.h_27), intros hyp.h_497,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b b) (product x b)) = (product (product b x) (product b b)))) (product b (quotient b1 b)) (quotient (product b b1) b) hyp.h_497 hyp.h_122), intros hyp.h_498,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b b) (product (product b (quotient b1 b)) b)) = (product x (product b b)))) (difference (product b1 b) b) (product b (product b (quotient b1 b))) hyp.h_496 hyp.h_498), intros hyp.h_499,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b b) x) = (product (difference (product b1 b) b) (product b b)))) (product b b1) (product (product b (quotient b1 b)) b) hyp.h_493 hyp.h_499), intros hyp.h_500,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product b b1)) = (product (difference (product b1 b) b) x))) b (product b b) hyp.h_101 hyp.h_500), intros hyp.h_501,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product b x) b) b) = (product b x))) (product b (quotient b1 b)) (quotient (product b b1) b) hyp.h_497 hyp.h_26), intros hyp.h_502,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient (product x b) b) = x)) (difference (product b1 b) b) (product b (product b (quotient b1 b))) hyp.h_496 hyp.h_502), intros hyp.h_503,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b) = (difference (product b1 b) b))) (product b (product b b1)) (product (difference (product b1 b) b) b) hyp.h_501 hyp.h_503), intros hyp.h_504,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (quotient (product b (product b b1)) b) x) = b)) (product b (product b b1)) (product (quotient (product b (product b b1)) b) b) hyp.h_54 hyp.h_250), intros hyp.h_505,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference x (product b (product b b1))) = b)) (difference (product b1 b) b) (quotient (product b (product b b1)) b) hyp.h_504 hyp.h_505), intros hyp.h_506,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient (quotient b1 b) b) b)) = (product (product b (quotient (quotient b1 b) b)) x))) b (product b b) hyp.h_101 hyp.h_120), intros hyp.h_507,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b x) = (product (product b (quotient (quotient b1 b) b)) b))) (quotient b1 b) (product (quotient (quotient b1 b) b) b) hyp.h_58 hyp.h_507), intros hyp.h_508,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product x b) (product b (product b (quotient (quotient b1 b) b)))) = b)) (quotient b1 b) (product (quotient (quotient b1 b) b) b) hyp.h_58 hyp.h_79), intros hyp.h_509,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product b (product b (quotient (quotient b1 b) b)))) = b)) b1 (product (quotient b1 b) b) hyp.h_57 hyp.h_509), intros hyp.h_510,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (product x b) (product (product x b) (product b (product b (quotient (quotient b1 b) b))))) = (product b (product b (quotient (quotient b1 b) b))))) (quotient b1 b) (product (quotient (quotient b1 b) b) b) hyp.h_58 hyp.h_255), intros hyp.h_511,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference x (product x (product b (product b (quotient (quotient b1 b) b))))) = (product b (product b (quotient (quotient b1 b) b))))) b1 (product (quotient b1 b) b) hyp.h_57 hyp.h_511), intros hyp.h_512,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference b1 x) = (product b (product b (quotient (quotient b1 b) b))))) b (product b1 (product b (product b (quotient (quotient b1 b) b)))) hyp.h_510 hyp.h_512), intros hyp.h_513,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b) = (product b (quotient (quotient b1 b) b)))) (product b (quotient b1 b)) (product (product b (quotient (quotient b1 b) b)) b) hyp.h_508 hyp.h_24), intros hyp.h_514,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (quotient (product b (quotient b1 b)) b) b)) = (product (product b (quotient (product b (quotient b1 b)) b)) x))) b (product b b) hyp.h_101 hyp.h_134), intros hyp.h_515,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product b (product x b)) = (product (product b x) b))) (product b (quotient (quotient b1 b) b)) (quotient (product b (quotient b1 b)) b) hyp.h_514 hyp.h_515), intros hyp.h_516,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b (product (product b (quotient (quotient b1 b) b)) b)) = (product x b))) (difference b1 b) (product b (product b (quotient (quotient b1 b) b))) hyp.h_513 hyp.h_516), intros hyp.h_517,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product b x) = (product (difference b1 b) b))) (product b (quotient b1 b)) (product (product b (quotient (quotient b1 b) b)) b) hyp.h_508 hyp.h_517), intros hyp.h_518,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, (x = (product (difference b1 b) b))) (difference (product b1 b) b) (product b (product b (quotient b1 b))) hyp.h_496 hyp.h_518), intros hyp.h_519,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((quotient (product (product b x) b) b) = (product b x))) (product b (quotient (quotient b1 b) b)) (quotient (product b (quotient b1 b)) b) hyp.h_514 hyp.h_22), intros hyp.h_520,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient (product x b) b) = x)) (difference b1 b) (product b (product b (quotient (quotient b1 b) b))) hyp.h_513 hyp.h_520), intros hyp.h_521,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b) = (difference b1 b))) (difference (product b1 b) b) (product (difference b1 b) b) hyp.h_519 hyp.h_521), intros hyp.h_522,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (difference x b)) = b)) (difference b1 b) (quotient (difference (product b1 b) b) b) hyp.h_522 hyp.h_224), intros hyp.h_523,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product x b) (product (difference x b) b1)) = (product (product x (difference x b)) (product b b1)))) (difference b1 b) (quotient (difference (product b1 b) b) b) hyp.h_522 hyp.h_159), intros hyp.h_524,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x (product (difference (difference b1 b) b) b1)) = (product (product (difference b1 b) (difference (difference b1 b) b)) (product b b1)))) (difference (product b1 b) b) (product (difference b1 b) b) hyp.h_519 hyp.h_524), intros hyp.h_525,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (difference (product b1 b) b) (product (difference (difference b1 b) b) b1)) = (product x (product b b1)))) b (product (difference b1 b) (difference (difference b1 b) b)) hyp.h_523 hyp.h_525), intros hyp.h_526,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference x (product x (product (difference (quotient (difference (product b1 b) b) b) b) b1))) = (product (difference (quotient (difference (product b1 b) b) b) b) b1))) (difference (product b1 b) b) (product (quotient (difference (product b1 b) b) b) b) hyp.h_60 hyp.h_251), intros hyp.h_527,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (difference (product b1 b) b) (product (difference (product b1 b) b) (product (difference x b) b1))) = (product (difference x b) b1))) (difference b1 b) (quotient (difference (product b1 b) b) b) hyp.h_522 hyp.h_527), intros hyp.h_528,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((difference (difference (product b1 b) b) x) = (product (difference (difference b1 b) b) b1))) (product b (product b b1)) (product (difference (product b1 b) b) (product (difference (difference b1 b) b) b1)) hyp.h_526 hyp.h_528), intros hyp.h_529,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, (x = (product (difference (difference b1 b) b) b1))) b (difference (difference (product b1 b) b) (product b (product b b1))) hyp.h_506 hyp.h_529), intros hyp.h_530,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((quotient x b1) = (difference (difference b1 b) b))) b (product (difference (difference b1 b) b) b1) hyp.h_530 hyp.h_33), intros hyp.h_531,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product x x) (product (product (quotient b b1) (difference b1 b)) b2)) = (product (product x (product (quotient b b1) (difference b1 b))) (product x b2)))) b1 (product b1 b1) hyp.h_100 hyp.h_207), intros hyp.h_532,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x (product (product (quotient b b1) (difference b1 b)) b2)) = (product (product b1 (product (quotient b b1) (difference b1 b))) (product b1 b2)))) b1 (product b1 b1) hyp.h_100 hyp.h_532), intros hyp.h_533,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 (quotient b b1)) x) = (product (product b1 b1) (product (quotient b b1) (difference b1 b))))) b (product b1 (difference b1 b)) hyp.h_223 hyp.h_179), intros hyp.h_534,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 (quotient b b1)) b) = (product x (product (quotient b b1) (difference b1 b))))) b1 (product b1 b1) hyp.h_100 hyp.h_534), intros hyp.h_535,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b1) x) = (product (product b1 (quotient b b1)) (product b1 b1)))) b (product (quotient b b1) b1) hyp.h_63 hyp.h_151), intros hyp.h_536,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product x b) = (product (product b1 (quotient b b1)) x))) b1 (product b1 b1) hyp.h_100 hyp.h_536), intros hyp.h_537,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product (product b1 (quotient b b1)) x) (product b b2)) = (product (product (product b1 (quotient b b1)) b) (product x b2)))) b1 (product b1 b1) hyp.h_100 hyp.h_209), intros hyp.h_538,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product x (product b b2)) = (product (product (product b1 (quotient b b1)) b) (product b1 b2)))) (product b1 b) (product (product b1 (quotient b b1)) b1) hyp.h_537 hyp.h_538), intros hyp.h_539,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b) (product b b2)) = (product x (product b1 b2)))) (product b1 (product (quotient b b1) (difference b1 b))) (product (product b1 (quotient b b1)) b) hyp.h_535 hyp.h_539), intros hyp.h_540,
apply (gapt.lk.EqualityLeftRule1 (λ x : i, ((product (product b1 b) (product b b2)) = x)) (product b1 (product (product (quotient b b1) (difference b1 b)) b2)) (product (product b1 (product (quotient b b1) (difference b1 b))) (product b1 b2)) hyp.h_533 hyp.h_540), intros hyp.h_541,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b) (product b b2)) = (product b1 (product (product x (difference b1 b)) b2)))) (difference (difference b1 b) b) (quotient b b1) hyp.h_531 hyp.h_541), intros hyp.h_542,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b) (product b b2)) = (product b1 (product x b2)))) b2 (product (difference (difference b1 b) b) (difference b1 b)) hyp.h_491 hyp.h_542), intros hyp.h_543,
apply (gapt.lk.EqualityLeftRule2 (λ x : i, ((product (product b1 b) (product b b2)) = (product b1 x))) b2 (product b2 b2) hyp.h_94 hyp.h_543), intros hyp.h_544,
apply (gapt.lk.LogicalAxiom hyp.h_544 hyp.h_281), intros hyp.h_281,
apply (gapt.lk.LogicalAxiom hyp.h_281 hyp.h_14), end

end gapt_export
